import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/providers/queryProvider";
import RecoilContextProvider from "@/providers/recoilProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body >
        <QueryProvider>
          <RecoilContextProvider>
            <ReactQueryDevtools initialIsOpen={false} />
          {children}
          </RecoilContextProvider>
        </QueryProvider>
        
        
      </body>
    </html>
  );
}
